// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// check_NaN_Inf
bool check_NaN_Inf(arma::mat x);
RcppExport SEXP _ClusterR_check_NaN_Inf(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(check_NaN_Inf(x));
    return rcpp_result_gen;
END_RCPP
}
// validate_centroids
arma::rowvec validate_centroids(arma::mat& data, arma::mat init_centroids);
RcppExport SEXP _ClusterR_validate_centroids(SEXP dataSEXP, SEXP init_centroidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type init_centroids(init_centroidsSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_centroids(data, init_centroids));
    return rcpp_result_gen;
END_RCPP
}
// SCALE
arma::mat SCALE(arma::mat data, bool mean_center, bool sd_scale);
RcppExport SEXP _ClusterR_SCALE(SEXP dataSEXP, SEXP mean_centerSEXP, SEXP sd_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type mean_center(mean_centerSEXP);
    Rcpp::traits::input_parameter< bool >::type sd_scale(sd_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(SCALE(data, mean_center, sd_scale));
    return rcpp_result_gen;
END_RCPP
}
// KMEANS_rcpp
Rcpp::List KMEANS_rcpp(arma::mat& data, int clusters, int num_init, int max_iters, std::string initializer, bool fuzzy, bool verbose, Rcpp::Nullable<Rcpp::NumericMatrix> CENTROIDS, double tol, double eps, double tol_optimal_init, int seed);
RcppExport SEXP _ClusterR_KMEANS_rcpp(SEXP dataSEXP, SEXP clustersSEXP, SEXP num_initSEXP, SEXP max_itersSEXP, SEXP initializerSEXP, SEXP fuzzySEXP, SEXP verboseSEXP, SEXP CENTROIDSSEXP, SEXP tolSEXP, SEXP epsSEXP, SEXP tol_optimal_initSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type num_init(num_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iters(max_itersSEXP);
    Rcpp::traits::input_parameter< std::string >::type initializer(initializerSEXP);
    Rcpp::traits::input_parameter< bool >::type fuzzy(fuzzySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type CENTROIDS(CENTROIDSSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type tol_optimal_init(tol_optimal_initSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(KMEANS_rcpp(data, clusters, num_init, max_iters, initializer, fuzzy, verbose, CENTROIDS, tol, eps, tol_optimal_init, seed));
    return rcpp_result_gen;
END_RCPP
}
// KMEANS_arma
arma::mat KMEANS_arma(arma::mat& data, int clusters, int n_iter, bool verbose, std::string seed_mode, Rcpp::Nullable<Rcpp::NumericMatrix> CENTROIDS, int seed);
RcppExport SEXP _ClusterR_KMEANS_arma(SEXP dataSEXP, SEXP clustersSEXP, SEXP n_iterSEXP, SEXP verboseSEXP, SEXP seed_modeSEXP, SEXP CENTROIDSSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< std::string >::type seed_mode(seed_modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type CENTROIDS(CENTROIDSSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(KMEANS_arma(data, clusters, n_iter, verbose, seed_mode, CENTROIDS, seed));
    return rcpp_result_gen;
END_RCPP
}
// opt_clust_fK
Rcpp::List opt_clust_fK(arma::vec sum_distortion, int data_num_cols, double threshold);
RcppExport SEXP _ClusterR_opt_clust_fK(SEXP sum_distortionSEXP, SEXP data_num_colsSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type sum_distortion(sum_distortionSEXP);
    Rcpp::traits::input_parameter< int >::type data_num_cols(data_num_colsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(opt_clust_fK(sum_distortion, data_num_cols, threshold));
    return rcpp_result_gen;
END_RCPP
}
// evaluation_rcpp
Rcpp::List evaluation_rcpp(arma::mat& data, arma::vec CLUSTER, bool silhouette);
RcppExport SEXP _ClusterR_evaluation_rcpp(SEXP dataSEXP, SEXP CLUSTERSEXP, SEXP silhouetteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type CLUSTER(CLUSTERSEXP);
    Rcpp::traits::input_parameter< bool >::type silhouette(silhouetteSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluation_rcpp(data, CLUSTER, silhouette));
    return rcpp_result_gen;
END_RCPP
}
// mini_batch_kmeans
Rcpp::List mini_batch_kmeans(arma::mat& data, int clusters, int batch_size, int max_iters, int num_init, double init_fraction, std::string initializer, int early_stop_iter, bool verbose, Rcpp::Nullable<Rcpp::NumericMatrix> CENTROIDS, double tol, double tol_optimal_init, int seed);
RcppExport SEXP _ClusterR_mini_batch_kmeans(SEXP dataSEXP, SEXP clustersSEXP, SEXP batch_sizeSEXP, SEXP max_itersSEXP, SEXP num_initSEXP, SEXP init_fractionSEXP, SEXP initializerSEXP, SEXP early_stop_iterSEXP, SEXP verboseSEXP, SEXP CENTROIDSSEXP, SEXP tolSEXP, SEXP tol_optimal_initSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_iters(max_itersSEXP);
    Rcpp::traits::input_parameter< int >::type num_init(num_initSEXP);
    Rcpp::traits::input_parameter< double >::type init_fraction(init_fractionSEXP);
    Rcpp::traits::input_parameter< std::string >::type initializer(initializerSEXP);
    Rcpp::traits::input_parameter< int >::type early_stop_iter(early_stop_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type CENTROIDS(CENTROIDSSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type tol_optimal_init(tol_optimal_initSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(mini_batch_kmeans(data, clusters, batch_size, max_iters, num_init, init_fraction, initializer, early_stop_iter, verbose, CENTROIDS, tol, tol_optimal_init, seed));
    return rcpp_result_gen;
END_RCPP
}
// Predict_mini_batch_kmeans
Rcpp::List Predict_mini_batch_kmeans(arma::mat& data, arma::mat& CENTROIDS, bool fuzzy, double eps);
RcppExport SEXP _ClusterR_Predict_mini_batch_kmeans(SEXP dataSEXP, SEXP CENTROIDSSEXP, SEXP fuzzySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CENTROIDS(CENTROIDSSEXP);
    Rcpp::traits::input_parameter< bool >::type fuzzy(fuzzySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Predict_mini_batch_kmeans(data, CENTROIDS, fuzzy, eps));
    return rcpp_result_gen;
END_RCPP
}
// GMM_arma
Rcpp::List GMM_arma(arma::mat& data, int gaussian_comps, std::string dist_mode, std::string seed_mode, int km_iter, int em_iter, bool verbose, double var_floor, int seed);
RcppExport SEXP _ClusterR_GMM_arma(SEXP dataSEXP, SEXP gaussian_compsSEXP, SEXP dist_modeSEXP, SEXP seed_modeSEXP, SEXP km_iterSEXP, SEXP em_iterSEXP, SEXP verboseSEXP, SEXP var_floorSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type gaussian_comps(gaussian_compsSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist_mode(dist_modeSEXP);
    Rcpp::traits::input_parameter< std::string >::type seed_mode(seed_modeSEXP);
    Rcpp::traits::input_parameter< int >::type km_iter(km_iterSEXP);
    Rcpp::traits::input_parameter< int >::type em_iter(em_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type var_floor(var_floorSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(GMM_arma(data, gaussian_comps, dist_mode, seed_mode, km_iter, em_iter, verbose, var_floor, seed));
    return rcpp_result_gen;
END_RCPP
}
// predict_MGausDPDF
Rcpp::List predict_MGausDPDF(arma::mat data, arma::mat CENTROIDS, arma::mat COVARIANCE, arma::vec WEIGHTS, double eps);
RcppExport SEXP _ClusterR_predict_MGausDPDF(SEXP dataSEXP, SEXP CENTROIDSSEXP, SEXP COVARIANCESEXP, SEXP WEIGHTSSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type CENTROIDS(CENTROIDSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type COVARIANCE(COVARIANCESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type WEIGHTS(WEIGHTSSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_MGausDPDF(data, CENTROIDS, COVARIANCE, WEIGHTS, eps));
    return rcpp_result_gen;
END_RCPP
}
// GMM_arma_AIC_BIC
arma::rowvec GMM_arma_AIC_BIC(arma::mat& data, arma::rowvec max_clusters, std::string dist_mode, std::string seed_mode, int km_iter, int em_iter, bool verbose, double var_floor, std::string criterion, int seed);
RcppExport SEXP _ClusterR_GMM_arma_AIC_BIC(SEXP dataSEXP, SEXP max_clustersSEXP, SEXP dist_modeSEXP, SEXP seed_modeSEXP, SEXP km_iterSEXP, SEXP em_iterSEXP, SEXP verboseSEXP, SEXP var_floorSEXP, SEXP criterionSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type max_clusters(max_clustersSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist_mode(dist_modeSEXP);
    Rcpp::traits::input_parameter< std::string >::type seed_mode(seed_modeSEXP);
    Rcpp::traits::input_parameter< int >::type km_iter(km_iterSEXP);
    Rcpp::traits::input_parameter< int >::type em_iter(em_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type var_floor(var_floorSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(GMM_arma_AIC_BIC(data, max_clusters, dist_mode, seed_mode, km_iter, em_iter, verbose, var_floor, criterion, seed));
    return rcpp_result_gen;
END_RCPP
}
// dissim_mat
arma::mat dissim_mat(arma::mat& data, std::string& method, double minkowski_p, bool upper, bool diagonal, int threads, double eps);
RcppExport SEXP _ClusterR_dissim_mat(SEXP dataSEXP, SEXP methodSEXP, SEXP minkowski_pSEXP, SEXP upperSEXP, SEXP diagonalSEXP, SEXP threadsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type minkowski_p(minkowski_pSEXP);
    Rcpp::traits::input_parameter< bool >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< bool >::type diagonal(diagonalSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(dissim_mat(data, method, minkowski_p, upper, diagonal, threads, eps));
    return rcpp_result_gen;
END_RCPP
}
// ClusterMedoids
Rcpp::List ClusterMedoids(arma::mat& data, int clusters, std::string method, double minkowski_p, int threads, bool verbose, bool swap_phase, bool fuzzy, int seed);
RcppExport SEXP _ClusterR_ClusterMedoids(SEXP dataSEXP, SEXP clustersSEXP, SEXP methodSEXP, SEXP minkowski_pSEXP, SEXP threadsSEXP, SEXP verboseSEXP, SEXP swap_phaseSEXP, SEXP fuzzySEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type minkowski_p(minkowski_pSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type swap_phase(swap_phaseSEXP);
    Rcpp::traits::input_parameter< bool >::type fuzzy(fuzzySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ClusterMedoids(data, clusters, method, minkowski_p, threads, verbose, swap_phase, fuzzy, seed));
    return rcpp_result_gen;
END_RCPP
}
// dissim_MEDOIDS
arma::mat dissim_MEDOIDS(arma::mat& data, std::string& method, arma::mat MEDOIDS, double minkowski_p, int threads, double eps);
RcppExport SEXP _ClusterR_dissim_MEDOIDS(SEXP dataSEXP, SEXP methodSEXP, SEXP MEDOIDSSEXP, SEXP minkowski_pSEXP, SEXP threadsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type MEDOIDS(MEDOIDSSEXP);
    Rcpp::traits::input_parameter< double >::type minkowski_p(minkowski_pSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(dissim_MEDOIDS(data, method, MEDOIDS, minkowski_p, threads, eps));
    return rcpp_result_gen;
END_RCPP
}
// ClaraMedoids
Rcpp::List ClaraMedoids(arma::mat& data, int clusters, std::string method, int samples, double sample_size, double minkowski_p, int threads, bool verbose, bool swap_phase, bool fuzzy, int seed);
RcppExport SEXP _ClusterR_ClaraMedoids(SEXP dataSEXP, SEXP clustersSEXP, SEXP methodSEXP, SEXP samplesSEXP, SEXP sample_sizeSEXP, SEXP minkowski_pSEXP, SEXP threadsSEXP, SEXP verboseSEXP, SEXP swap_phaseSEXP, SEXP fuzzySEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< double >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type minkowski_p(minkowski_pSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type swap_phase(swap_phaseSEXP);
    Rcpp::traits::input_parameter< bool >::type fuzzy(fuzzySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ClaraMedoids(data, clusters, method, samples, sample_size, minkowski_p, threads, verbose, swap_phase, fuzzy, seed));
    return rcpp_result_gen;
END_RCPP
}
// predict_medoids
Rcpp::List predict_medoids(arma::mat& data, std::string method, arma::mat MEDOIDS, double minkowski_p, int threads, bool fuzzy, double eps);
RcppExport SEXP _ClusterR_predict_medoids(SEXP dataSEXP, SEXP methodSEXP, SEXP MEDOIDSSEXP, SEXP minkowski_pSEXP, SEXP threadsSEXP, SEXP fuzzySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type MEDOIDS(MEDOIDSSEXP);
    Rcpp::traits::input_parameter< double >::type minkowski_p(minkowski_pSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type fuzzy(fuzzySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_medoids(data, method, MEDOIDS, minkowski_p, threads, fuzzy, eps));
    return rcpp_result_gen;
END_RCPP
}
// split_rcpp_lst
Rcpp::List split_rcpp_lst(Rcpp::List lst);
RcppExport SEXP _ClusterR_split_rcpp_lst(SEXP lstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type lst(lstSEXP);
    rcpp_result_gen = Rcpp::wrap(split_rcpp_lst(lst));
    return rcpp_result_gen;
END_RCPP
}
// OptClust
Rcpp::List OptClust(arma::mat& data, arma::rowvec iter_clust, std::string method, bool clara, int samples, double sample_size, double minkowski_p, std::string criterion, int threads, bool swap_phase, bool verbose, int seed);
RcppExport SEXP _ClusterR_OptClust(SEXP dataSEXP, SEXP iter_clustSEXP, SEXP methodSEXP, SEXP claraSEXP, SEXP samplesSEXP, SEXP sample_sizeSEXP, SEXP minkowski_pSEXP, SEXP criterionSEXP, SEXP threadsSEXP, SEXP swap_phaseSEXP, SEXP verboseSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type iter_clust(iter_clustSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type clara(claraSEXP);
    Rcpp::traits::input_parameter< int >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< double >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type minkowski_p(minkowski_pSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type swap_phase(swap_phaseSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(OptClust(data, iter_clust, method, clara, samples, sample_size, minkowski_p, criterion, threads, swap_phase, verbose, seed));
    return rcpp_result_gen;
END_RCPP
}
// affinity_propagation
Rcpp::List affinity_propagation(arma::mat& s, std::vector<double> p, int maxits, int convits, double dampfact, bool details, double nonoise, double eps, bool time);
RcppExport SEXP _ClusterR_affinity_propagation(SEXP sSEXP, SEXP pSEXP, SEXP maxitsSEXP, SEXP convitsSEXP, SEXP dampfactSEXP, SEXP detailsSEXP, SEXP nonoiseSEXP, SEXP epsSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type maxits(maxitsSEXP);
    Rcpp::traits::input_parameter< int >::type convits(convitsSEXP);
    Rcpp::traits::input_parameter< double >::type dampfact(dampfactSEXP);
    Rcpp::traits::input_parameter< bool >::type details(detailsSEXP);
    Rcpp::traits::input_parameter< double >::type nonoise(nonoiseSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(affinity_propagation(s, p, maxits, convits, dampfact, details, nonoise, eps, time));
    return rcpp_result_gen;
END_RCPP
}
// preferenceRange
std::vector<double> preferenceRange(arma::mat& s, std::string method, int threads);
RcppExport SEXP _ClusterR_preferenceRange(SEXP sSEXP, SEXP methodSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(preferenceRange(s, method, threads));
    return rcpp_result_gen;
END_RCPP
}
