# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_NaN_Inf <- function(x) {
    .Call(`_ClusterR_check_NaN_Inf`, x)
}

validate_centroids <- function(data, init_centroids, threads) {
    .Call(`_ClusterR_validate_centroids`, data, init_centroids, threads)
}

SCALE <- function(data, mean_center = TRUE, sd_scale = TRUE) {
    .Call(`_ClusterR_SCALE`, data, mean_center, sd_scale)
}

KMEANS_rcpp <- function(data, clusters, num_init = 1L, max_iters = 200L, initializer = "kmeans++", fuzzy = FALSE, verbose = FALSE, CENTROIDS = NULL, tol = 1e-4, eps = 1.0e-6, tol_optimal_init = 0.5, seed = 1L) {
    .Call(`_ClusterR_KMEANS_rcpp`, data, clusters, num_init, max_iters, initializer, fuzzy, verbose, CENTROIDS, tol, eps, tol_optimal_init, seed)
}

KMEANS_arma <- function(data, clusters, n_iter, verbose, seed_mode = "random_subset", CENTROIDS = NULL, seed = 1L) {
    .Call(`_ClusterR_KMEANS_arma`, data, clusters, n_iter, verbose, seed_mode, CENTROIDS, seed)
}

opt_clust_fK <- function(sum_distortion, data_num_cols, threshold = 0.85) {
    .Call(`_ClusterR_opt_clust_fK`, sum_distortion, data_num_cols, threshold)
}

evaluation_rcpp <- function(data, CLUSTER, silhouette = FALSE) {
    .Call(`_ClusterR_evaluation_rcpp`, data, CLUSTER, silhouette)
}

mini_batch_kmeans <- function(data, clusters, batch_size, max_iters, num_init = 1L, init_fraction = 1.0, initializer = "kmeans++", early_stop_iter = 10L, verbose = FALSE, CENTROIDS = NULL, tol = 1e-4, tol_optimal_init = 0.5, seed = 1L) {
    .Call(`_ClusterR_mini_batch_kmeans`, data, clusters, batch_size, max_iters, num_init, init_fraction, initializer, early_stop_iter, verbose, CENTROIDS, tol, tol_optimal_init, seed)
}

Predict_mini_batch_kmeans <- function(data, CENTROIDS, fuzzy = FALSE, eps = 1.0e-6) {
    .Call(`_ClusterR_Predict_mini_batch_kmeans`, data, CENTROIDS, fuzzy, eps)
}

GMM_arma <- function(data, gaussian_comps, dist_mode, seed_mode, km_iter, em_iter, verbose, var_floor = 1e-10, seed = 1L) {
    .Call(`_ClusterR_GMM_arma`, data, gaussian_comps, dist_mode, seed_mode, km_iter, em_iter, verbose, var_floor, seed)
}

predict_MGausDPDF <- function(data, CENTROIDS, COVARIANCE, WEIGHTS, eps = 1.0e-8) {
    .Call(`_ClusterR_predict_MGausDPDF`, data, CENTROIDS, COVARIANCE, WEIGHTS, eps)
}

GMM_arma_AIC_BIC <- function(data, max_clusters, dist_mode, seed_mode, km_iter, em_iter, verbose, var_floor = 1e-10, criterion = "AIC", seed = 1L) {
    .Call(`_ClusterR_GMM_arma_AIC_BIC`, data, max_clusters, dist_mode, seed_mode, km_iter, em_iter, verbose, var_floor, criterion, seed)
}

dissim_mat <- function(data, method, minkowski_p = 1.0, upper = TRUE, diagonal = TRUE, threads = 1L, eps = 1.0e-6) {
    .Call(`_ClusterR_dissim_mat`, data, method, minkowski_p, upper, diagonal, threads, eps)
}

ClusterMedoids <- function(data, clusters, method, minkowski_p = 1.0, threads = 1L, verbose = FALSE, swap_phase = FALSE, fuzzy = FALSE, seed = 1L) {
    .Call(`_ClusterR_ClusterMedoids`, data, clusters, method, minkowski_p, threads, verbose, swap_phase, fuzzy, seed)
}

dissim_MEDOIDS <- function(data, method, MEDOIDS, minkowski_p = 1.0, threads = 1L, eps = 1.0e-6) {
    .Call(`_ClusterR_dissim_MEDOIDS`, data, method, MEDOIDS, minkowski_p, threads, eps)
}

ClaraMedoids <- function(data, clusters, method, samples, sample_size, minkowski_p = 1.0, threads = 1L, verbose = FALSE, swap_phase = FALSE, fuzzy = FALSE, seed = 1L) {
    .Call(`_ClusterR_ClaraMedoids`, data, clusters, method, samples, sample_size, minkowski_p, threads, verbose, swap_phase, fuzzy, seed)
}

predict_medoids <- function(data, method, MEDOIDS, minkowski_p = 1.0, threads = 1L, fuzzy = FALSE, eps = 1.0e-6) {
    .Call(`_ClusterR_predict_medoids`, data, method, MEDOIDS, minkowski_p, threads, fuzzy, eps)
}

split_rcpp_lst <- function(lst) {
    .Call(`_ClusterR_split_rcpp_lst`, lst)
}

OptClust <- function(data, iter_clust, method, clara = FALSE, samples = 5L, sample_size = 0.001, minkowski_p = 1.0, criterion = "dissimilarity", threads = 1L, swap_phase = FALSE, verbose = FALSE, seed = 1L) {
    .Call(`_ClusterR_OptClust`, data, iter_clust, method, clara, samples, sample_size, minkowski_p, criterion, threads, swap_phase, verbose, seed)
}

affinity_propagation <- function(s, p, maxits = 1000L, convits = 100L, dampfact = 0.9, details = FALSE, nonoise = 0.0, eps = 2.2204e-16, time = FALSE) {
    .Call(`_ClusterR_affinity_propagation`, s, p, maxits, convits, dampfact, details, nonoise, eps, time)
}

preferenceRange <- function(s, method = "bound", threads = 1L) {
    .Call(`_ClusterR_preferenceRange`, s, method, threads)
}

